# Generated by Django 2.0.5 on 2018-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=30, verbose_name='姓 名')),
                ('account', models.IntegerField(default=True, unique=True, verbose_name='工 号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出 生 日 期')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=30, verbose_name='性 别')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='部 门')),
                ('position', models.CharField(blank=True, max_length=30, null=True, verbose_name='职位')),
                ('mobile', models.CharField(blank=True, default=True, max_length=11, verbose_name='电 话')),
            ],
        ),
    ]
